"""Generate DE/IT glossaries and write gameplay-i18n-de-it-overrides.json."""
from __future__ import annotations

import ast
import json
import re
from pathlib import Path

from gameplay_i18n_engine import FR_GLOSSARY, KEEP, TOKEN_RE

SCRIPTS = Path(__file__).resolve().parent
LOC = SCRIPTS.parent / "src" / "locales"


def collect_leaves(obj, out=None):
    if out is None:
        out = set()
    if isinstance(obj, dict):
        for v in obj.values():
            collect_leaves(v, out)
    elif isinstance(obj, str):
        out.add(obj)
    return out


def protect(text: str) -> tuple[str, list[str]]:
    tokens: list[str] = []

    def repl(m: re.Match[str]) -> str:
        tokens.append(m.group(0))
        return f"\x00{len(tokens) - 1}\x00"

    return TOKEN_RE.sub(repl, text), tokens


def restore(text: str, tokens: list[str]) -> str:
    for i, t in enumerate(tokens):
        text = text.replace(f"\x00{i}\x00", t)
    return text


def apply_glossary(text: str, glossary: dict[str, str]) -> str:
    for src, dst in sorted(glossary.items(), key=lambda x: -len(x[0])):
        text = text.replace(src, dst)
    return text


def load_en_strings() -> list[str]:
    ext = (SCRIPTS / "extend-gameplay-i18n.py").read_text().replace("Path(__file__)", "Path('.')")
    ns: dict = {}
    exec(ext.split("def deep_merge")[0], ns)
    en_map = {**ns["EN_MAP"], **json.loads((SCRIPTS / "gameplay-i18n-en-complete.json").read_text())}
    src = (SCRIPTS / "build-gameplay-i18n-fr-de-it.py").read_text()
    m = re.search(r"EN_FIX = (\{.*?\})\nEN_MAP\.update", src, re.S)
    en_map.update(ast.literal_eval(m.group(1)))
    es = json.loads((LOC / "gameplay.es.json").read_text(encoding="utf-8"))
    return sorted(set(en_map.get(s, s) for s in collect_leaves(es)))


# EN -> DE football manager glossary (longest phrases first at apply time)
DE_GLOSSARY: dict[str, str] = {
    " · unsaved": " · nicht gespeichert",
    "+ New": "+ Neu",
    "+ Academy level (better base stats)": "+ Akademie-Level (bessere Basiswerte)",
    "+1 opponent report per matchday": "+1 Gegnerbericht pro Spieltag",
    "+1 scheduled sub (4 rules)": "+1 geplanter Wechsel (4 Regeln)",
    "+1 team talk per season": "+1 Mannschaftsansprache pro Saison",
    "+10 slots for new prospects": "+10 Plätze für neue Talente",
    "+2 active plays per match (10)": "+2 aktive Spielzüge pro Spiel (10)",
    "+5% image rights": "+5 % Image-Rechte",
    "3D unavailable in this browser — showing portrait.": "3D in diesem Browser nicht verfügbar — Portrait wird angezeigt.",
    "A coach can only have 6 players assigned": "Ein Trainer darf nur 6 Spieler zugewiesen haben",
    "ACTIVE TEAM TALK (until T{{turn}})": "AKTIVE MANNSCHAFTSANSPIRACHE (bis T{{turn}})",
    "AUTO-REFRESH": "AUTO-AKTUALISIERUNG",
    "AVAILABLE": "VERFÜGBAR",
    "AWARDED": "VERGEBEN",
    "AWARDED TO YOU": "AN DICH VERGEBEN",
    "Academy": "Akademie",
    "Academy & Youth": "Akademie & Jugend",
    "Academy closed": "Akademie geschlossen",
    "Accept this transfer proposal? The move will be executed irreversibly.": "Diesen Transfervorschlag annehmen? Der Wechsel wird unwiderruflich ausgeführt.",
    "Accept transfer": "Transfer annehmen",
    "Accepted or rejected negotiations will appear here.": "Angenommene oder abgelehnte Verhandlungen erscheinen hier.",
    "Achievements": "Erfolge",
    "Achievements ({{count}})": "Erfolge ({{count}})",
    "Action": "Entscheidung",
    "Activate for match": "Für Spiel aktivieren",
    "Active": "Aktiv",
    "Added to targets and scout assigned.": "Zu Zielen hinzugefügt und Scout zugewiesen.",
    "Advance matchday": "Spieltag vorrücken",
    "Advance report": "Bericht vertiefen",
    "Advanced": "Erweitert",
    "Advanced board": "Erweitertes Taktikbrett",
    "Age": "Alter",
    "Agent demands": "Agentenforderungen",
    "Agents accept 5% less salary": "Agenten akzeptieren 5 % weniger Gehalt",
    "All": "Alle",
    "Also motivates similar players in August": "Motiviert ähnliche Spieler auch im August",
    "An 8% penalty will apply for each remaining year. Confirm termination?": "Für jedes verbleibende Jahr fällt eine Strafe von 8 % an. Kündigung bestätigen?",
    "Analysis": "Analyse",
    "Annual wage": "Jahresgehalt",
    "Architectural level": "Architektur-Level",
    "Architectural upgrade completed": "Architektur-Upgrade abgeschlossen",
    "Assigned resident": "Zugewiesener Bewohner",
    "Assistants": "Assistenten",
    "Assists": "Vorlagen",
    "Ast": "Vorl.",
    "Attendance": "Zuschauer",
    "Attendance bonuses": "Zuschauerboni",
    "Auctions unavailable": "Auktionen nicht verfügbar",
    "Authorize funds": "Mittel freigeben",
    "Available": "Verfügbar",
    "Available on: {{date}}": "Verfügbar ab: {{date}}",
    "Available room": "Freies Zimmer",
    "Average": "Durchschnitt",
    "Average fitness": "Durchschnittliche Fitness",
    "Average morale": "Durchschnittliche Moral",
    "Away": "Ausw.",
    "Away kit": "Auswärtstrikot",
    "Backroom staff": "Betreuungsstab",
    "Banner copied to clipboard!": "Banner in die Zwischenablage kopiert!",
    "Base talent": "Basistalent",
    "Be the first to get a share package.": "Sei der Erste, der ein Aktienpaket erhält.",
    "Best average rating": "Beste Durchschnittsnote",
    "Bid": "Bieten",
    "Bid amount (€)": "Gebotsbetrag (€)",
    "Bid sent": "Gebot gesendet",
    "Bid {{amount}} for {{player}}? The amount will be sealed until closing.": "{{amount}} für {{player}} bieten? Der Betrag bleibt bis zum Abschluss versiegelt.",
    "Board objective: {{objective}}": "Vorstandsziel: {{objective}}",
    "Born salesperson": "Geborener Verkäufer",
    "Bracket": "Turnierbaum",
    "Break": "Abbrechen",
    "Break contract": "Vertrag kündigen",
    "Break image rights contract": "Image-Rechte-Vertrag kündigen",
    "Break off talks": "Verhandlungen abbrechen",
    "Build": "Bauen",
    "CAREER TOTAL": "KARRIERE GESAMT",
    "CLOSED": "GESCHLOSSEN",
    "CLOSED (until T{{turn}})": "GESCHLOSSEN (bis T{{turn}})",
    "COMPLETED": "ABGESCHLOSSEN",
    "Calculating...": "Berechnung…",
    "Calendar": "Kalender",
    "Calendar view": "Kalenderansicht",
    "Calm": "Ruhe",
    "Campus facilities": "Campus-Anlagen",
    "Cancel outsource": "Outsourcing kündigen",
    "Cancel service": "Service kündigen",
    "Cancel {{name}}? You will stop paying the monthly cost.": "{{name}} kündigen? Die monatlichen Kosten entfallen.",
    "Capacity": "Kapazität",
    "Career path": "Karriereverlauf",
    "Cash": "Kasse",
    "Categories covered": "Abgedeckte Kategorien",
    "Champions League zone, position {{pos}}": "Champions-League-Zone, Position {{pos}}",
    "Choose another competition or wait for the next turn.": "Wähle einen anderen Wettbewerb oder warte auf die nächste Runde.",
    "Choose club and player.": "Verein und Spieler wählen.",
    "Close Training ({{uses}}/2)": "Training schließen ({{uses}}/2)",
    "Close training": "Training schließen",
    "Close training behind closed doors?": "Training hinter verschlossenen Türen schließen?",
    "Closed": "Geschlossen",
    "Club financial report": "Finanzbericht des Vereins",
    "Club profile": "Vereinsprofil",
    "Coach dismissed": "Trainer entlassen",
    "Coach hired": "Trainer verpflichtet",
    "Coach not found": "Trainer nicht gefunden",
    "Coach of {{club}}": "Trainer von {{club}}",
    "Coaches": "Trainer",
    "Collecting recent events...": "Aktuelle Ereignisse werden gesammelt…",
    "Competition unavailable": "Wettbewerb nicht verfügbar",
    "Competitions": "Wettbewerbe",
    "Confirm bid": "Gebot bestätigen",
    "Confirm board authorization to invest {{amount}} in {{project}}?": "Vorstandsfreigabe bestätigen, {{amount}} in {{project}} zu investieren?",
    "Confirm dismissal? The corresponding severance will apply.": "Entlassung bestätigen? Die entsprechende Abfindung wird fällig.",
    "Confirm loan": "Leihe bestätigen",
    "Confirm payment": "Zahlung bestätigen",
    "Confirm release clause payment": "Ausstiegsklausel-Zahlung bestätigen",
    "Confirm share purchase?": "Aktienkauf bestätigen?",
    "Confirm share sale?": "Aktienverkauf bestätigen?",
    "Continue to dashboard": "Weiter zum Dashboard",
    "Contract": "Vertrag",
    "Contract ends": "Vertragsende",
    "Contracts": "Verträge",
    "Corner kick": "Ecke",
    "Could not bid": "Gebot nicht möglich",
    "Could not create tactics": "Taktik konnte nicht erstellt werden",
    "Could not follow player.": "Spieler konnte nicht verfolgt werden.",
    "Could not load academy": "Akademie konnte nicht geladen werden",
    "Could not load backroom staff": "Betreuungsstab konnte nicht geladen werden",
    "Could not load calendar": "Kalender konnte nicht geladen werden",
    "Could not load career": "Karriere konnte nicht geladen werden",
    "Could not load competition": "Wettbewerb konnte nicht geladen werden",
    "Could not load competitions": "Wettbewerbe konnten nicht geladen werden",
    "Could not load kits": "Trikots konnten nicht geladen werden",
    "Could not load market": "Transfermarkt konnte nicht geladen werden",
    "Could not load matches": "Spiele konnten nicht geladen werden",
    "Could not load player": "Spieler konnte nicht geladen werden",
    "Could not load plays": "Spielzüge konnten nicht geladen werden",
    "Could not load scouting": "Scouting konnte nicht geladen werden",
    "Could not load squad": "Kader konnte nicht geladen werden",
    "Could not load standings": "Tabelle konnte nicht geladen werden",
    "Could not load tactics": "Taktik konnte nicht geladen werden",
    "Could not load targets list": "Zielliste konnte nicht geladen werden",
    "Could not load training": "Training konnte nicht geladen werden",
    "Could not make the change": "Änderung nicht möglich",
    "Could not read in-game date from server; use the Matchday list view.": "Spieldatum vom Server nicht lesbar; nutze die Spieltags-Listenansicht.",
    "Could not renew.": "Verlängerung nicht möglich.",
    "Could not replay match": "Spiel konnte nicht wiederholt werden",
    "Could not save drawing": "Zeichnung konnte nicht gespeichert werden",
    "Could not save midfield": "Mittelfeld konnte nicht gespeichert werden",
    "Could not save tactics": "Taktik konnte nicht gespeichert werden",
    "Could not set as primary": "Als Haupttaktik setzen nicht möglich",
    "Could not share match": "Spiel konnte nicht geteilt werden",
    "Could not start construction": "Bauarbeiten konnten nicht gestartet werden",
    "Could not start play": "Spielzug konnte nicht gestartet werden",
    "Could not toggle play": "Spielzug umschalten nicht möglich",
    "Could not unlock": "Freischalten nicht möglich",
    "Counter-attack": "Konter",
    "Country": "Land",
    "Current bench": "Aktuelle Bank",
    "Current level": "Aktuelles Level",
    "Current residents": "Aktuelle Bewohner",
    "D": "U",
    "DERBY": "DERBY",
    "Daily": "Täglich",
    "Date": "Datum",
    "Deactivate": "Deaktivieren",
    "Denial published": "Dementi veröffentlicht",
    "Derby": "Derby",
    "Design saved": "Zeichnung gespeichert",
    "Destination club": "Zielverein",
    "Development": "Entwicklung",
    "Development tree": "Entwicklungsbaum",
    "Direct free kick": "Direkter Freistoß",
    "Direct rival": "Direkter Rivale",
    "Director's office": "Büro des Sportdirektors",
    "Dismiss": "Entlassen",
    "Dismiss staff member": "Mitarbeiter entlassen",
    "Drag to rotate · scroll to zoom": "Ziehen zum Drehen · Scrollen zum Zoomen",
    "Dressing room": "Kabine",
    "Dressing room and morale management": "Kabinen- und Moralmanagement",
    "Dressing room leader": "Kabinenführer",
    "Dribbling": "Dribbling",
    "Duration (years)": "Laufzeit (Jahre)",
    "Economy and negotiation": "Wirtschaft und Verhandlung",
    "Economy summary": "Wirtschaftsübersicht",
    "Economy unavailable": "Wirtschaft nicht verfügbar",
    "Elite psychologist": "Elite-Psychologe",
    "Empty squad": "Leerer Kader",
    "Error advancing matchday: {{msg}}": "Fehler beim Vorrücken des Spieltags: {{msg}}",
    "Error dismissing.": "Fehler bei der Entlassung.",
    "Error hiring. Check your budget.": "Fehler bei der Verpflichtung. Budget prüfen.",
    "Error loading shares": "Fehler beim Laden der Aktien",
    "Error simulating: {{msg}}": "Fehler bei der Simulation: {{msg}}",
    "Euphoria": "Euphorie",
    "Europa League zone, position {{pos}}": "Europa-League-Zone, Position {{pos}}",
    "Event summary since your last session ({{since}}).": "Ereignisübersicht seit deiner letzten Sitzung ({{since}}).",
    "Expand dormitories": "Schlafsäle erweitern",
    "Expansion": "Erweiterung",
    "Expansion plan approval": "Genehmigung des Erweiterungsplans",
    "Experience": "Erfahrung",
    "FDF Sports Complex": "FDF-Sportkomplex",
    "FDF archives: talent generation": "FDF-Archive: Talentsgenerierung",
    "Facilities are empty. Scouts are searching for talent.": "Anlagen sind leer. Scouts suchen nach Talenten.",
    "Facility status": "Anlagenstatus",
    "Failed to calculate optimal lineup": "Optimale Aufstellung konnte nicht berechnet werden",
    "Failed to save tactics: {{msg}}": "Taktik speichern fehlgeschlagen: {{msg}}",
    "Fan sentiment": "Fan-Stimmung",
    "Featured match": "Topspiel",
    "Fewer filters": "Weniger Filter",
    "Finance king": "Finanzkönig",
    "Finishing": "Abschluss",
    "First team": "Profis",
    "Fitness report": "Fitnessbericht",
    "Fitness {{fitness}}% · Muscular {{muscular}}%.": "Fitness {{fitness}} % · Muskulär {{muscular}} %.",
    "Follow": "Folgen",
    "Following...": "Folge…",
    "Foot": "Fuß",
    "For sale": "Zu verkaufen",
    "For {{player}}": "Für {{player}}",
    "Free Agent": "Freisteller",
    "Free agent": "Freisteller",
    "Free agent — direct signing with no transfer fee (counts toward wage cap):": "Freisteller — direkte Verpflichtung ohne Ablöse (zählt zur Gehaltsobergrenze):",
    "Free agents": "Freisteller",
    "Front page": "Titelseite",
    "Front page copied to clipboard!": "Titelseite in die Zwischenablage kopiert!",
    "Full profile →": "Vollständiges Profil →",
    "GA": "GT",
    "GC": "GC",
    "GP": "Sp",
    "Get to know each player before picking the XI. The dressing room view is your reference; the table is for cold analysis.": "Lerne jeden Spieler kennen, bevor du die Elf aufstellst. Die Kabinenansicht ist deine Referenz; die Tabelle dient der nüchternen Analyse.",
    "Give Team Talk ({{uses}}/2)": "Mannschaftsansprache halten ({{uses}}/2)",
    "Give a motivational team talk to the home squad?": "Motivierende Mannschaftsansprache an die Heimmannschaft halten?",
    "Give home team talk": "Heim-Mannschaftsansprache",
    "Go": "Los",
    "Go to Market": "Zum Transfermarkt",
    "Go to Match Center": "Zum Spielzentrum",
    "Go to goal of the week": "Zum Tor der Woche",
    "Go to market": "Zum Transfermarkt",
    "Go to the search or another team's squad and click 'Follow' on a player.": "Gehe zur Suche oder zum Kader eines anderen Teams und klicke bei einem Spieler auf „Folgen“.",
    "Goal": "Tor",
    "Goal of the week": "Tor der Woche",
    "Goalkeeping": "Torwart",
    "Goals": "Tore",
    "Goals are going in": "Die Tore fallen",
    "Has not played yet.": "Noch nicht gespielt.",
    "Hire": "Verpflichten",
    "Hire a scout to create missions.": "Verpflichte einen Scout, um Missionen zu erstellen.",
    "Hire coaches by category to improve your players in each session.": "Verpflichte Trainer nach Kategorie, um deine Spieler in jeder Einheit zu verbessern.",
    "Hire outsource": "Outsourcing beauftragen",
    "Hire {{name}} for {{cost}}/mo?": "{{name}} für {{cost}}/Mo. verpflichten?",
    "History": "Historie",
    "Home": "Heim",
    "Home kit": "Heimtrikot",
    "Honours": "Titel",
    "Hot lines, clauses and rumors on the director's desk. Squad futures are decided here — with the transfer window clock always ticking.": "Heiße Leitungen, Klauseln und Gerüchte auf dem Schreibtisch des Direktors. Kaderzukunft wird hier entschieden — mit stets tickender Transferuhr.",
    "IN PLAY": "IM SPIEL",
    "Image rights": "Image-Rechte",
    "Immediate and irrevocable payment.": "Sofortige und unwiderrufliche Zahlung.",
    "In progress": "In Bearbeitung",
    "In-game date: {{date}}": "Spieldatum: {{date}}",
    "In-house scout": "Eigener Scout",
    "Injured": "Verletzt",
    "Injuries and suspensions": "Verletzungen und Sperren",
    "Installed capacity": "Installierte Kapazität",
    "Insufficient balance for this purchase": "Unzureichendes Guthaben für diesen Kauf",
    "Invalid amount.": "Ungültiger Betrag.",
    "Invalid competition": "Ungültiger Wettbewerb",
    "Invalid counter-offer amount.": "Ungültiger Gegenangebotsbetrag.",
    "Invest": "Investieren",
    "Invest club funds to expand facilities and improve youth training quality.": "Investiere Vereinsmittel, um Anlagen zu erweitern und die Jugendtrainingsqualität zu verbessern.",
    "Knockout": "K.-o.-Runde",
    "Knockout rounds not yet drawn": "K.-o.-Runden noch nicht ausgelost",
    "Knockout ties will appear once drawn.": "K.-o.-Paarungen erscheinen nach der Auslosung.",
    "L": "N",
    "LEVEL {{level}}": "LEVEL {{level}}",
    "LIVE": "LIVE",
    "LOANS": "LEIHEN",
    "Latest news": "Neueste Nachrichten",
    "League": "Liga",
    "League phase": "Ligaphase",
    "League phase (36)": "Ligaphase (36)",
    "League standings": "Ligatabelle",
    "Left": "Links",
    "Level": "Level",
    "Level {{level}}": "Level {{level}}",
    "List for sale from your Squad.": "Aus deinem Kader zum Verkauf anbieten.",
    "Live": "Live",
    "Live Matchday": "Live-Spieltag",
    "Live auctions": "Live-Auktionen",
    "Loading stadium information...": "Stadioninformationen werden geladen…",
    "Loading tactics board...": "Taktikbrett wird geladen…",
    "Loan player": "Spieler verleihen",
    "Loan {{player}} to {{club}}? The destination club will cover the wage until end of season.": "{{player}} an {{club}} verleihen? Der Zielverein übernimmt das Gehalt bis Saisonende.",
    "Loaned players": "Verliehene Spieler",
    "Loans": "Leihen",
    "MAXED": "MAXIMUM",
    "MY SQUAD": "MEIN KADER",
    "Manager career": "Manager-Karriere",
    "Manager rankings": "Manager-Rangliste",
    "Market": "Transfermarkt",
    "Market info": "Marktinfos",
    "Market shark": "Markt-Hai",
    "Market value": "Marktwert",
    "Match": "Spiel",
    "Match link copied to clipboard": "Spiel-Link in die Zwischenablage kopiert",
    "Match not found": "Spiel nicht gefunden",
    "Matchday processed — {{count}} match(es) played": "Spieltag verarbeitet — {{count}} Spiel(e) absolviert",
    "Matchday {{n}}": "Spieltag {{n}}",
    "Matchday {{week}}": "Spieltag {{week}}",
    "Matchdays": "Spieltage",
    "Max age": "Max. Alter",
    "Max value (€)": "Max. Wert (€)",
    "Maximum": "Maximum",
    "Maximum {{max}} active plays per match (FDF rule). Deactivate another first.": "Maximal {{max}} aktive Spielzüge pro Spiel (FDF-Regel). Deaktiviere zuerst einen anderen.",
    "Min age": "Min. Alter",
    "Min average": "Min. Durchschnitt",
    "Min dribbling": "Min. Dribbling",
    "Min passing": "Min. Passspiel",
    "Min potential": "Min. Potenzial",
    "Min shooting": "Min. Schuss",
    "Min tackling": "Min. Tackling",
    "Monthly wages": "Monatsgehälter",
    "Morale drops more slowly after defeats": "Moral sinkt nach Niederlagen langsamer",
    "Motivator": "Motivator",
    "Movement": "Laufwege",
    "Multiplayer": "Mehrspieler",
    "Must-have": "Unverzichtbar",
    "My Career": "Meine Karriere",
    "My Matches": "Meine Spiele",
    "My offers": "Meine Angebote",
    "NEW OFFER": "NEUES ANGEBOT",
    "NEXT MATCH": "NÄCHSTES SPIEL",
    "NOT FOR SALE": "NICHT ZU VERKAUFEN",
    "NPC bench": "NPC-Bank",
    "Name": "Name",
    "Navigate with ‹ › or press TODAY to return to the current date.": "Mit ‹ › navigieren oder HEUTE drücken, um zum aktuellen Datum zurückzukehren.",
    "Negotiate signing": "Verpflichtung verhandeln",
    "Negotiations": "Verhandlungen",
    "Negotiations unavailable": "Verhandlungen nicht verfügbar",
    "Negotiator": "Verhandler",
    "Net worth": "Vermögen",
    "New play": "Neuer Spielzug",
    "News": "Nachricht",
    "Next": "Weiter",
    "Next matchday": "Nächster Spieltag",
    "Next month": "Nächster Monat",
    "No achievements yet. Your first title awaits.": "Noch keine Erfolge. Dein erster Titel wartet.",
    "No active auctions right now. Create one from a player listed on the market.": "Derzeit keine aktiven Auktionen. Erstelle eine über einen Spieler auf dem Markt.",
    "No active offers": "Keine aktiven Angebote",
    "No auctions": "Keine Auktionen",
    "No auctions in this filter.": "Keine Auktionen in diesem Filter.",
    "No backroom staff": "Kein Betreuungsstab",
    "No bids yet. Be the first!": "Noch keine Gebote. Sei der Erste!",
    "No bracket available": "Kein Turnierbaum verfügbar",
    "No career data": "Keine Karrieredaten",
    "No club": "Kein Verein",
    "No data.": "Keine Daten.",
    "No development history yet — the curve grows with training and minutes.": "Noch keine Entwicklungshistorie — die Kurve wächst mit Training und Einsatzminuten.",
    "No free agents": "Keine Freisteller",
    "No history": "Keine Historie",
    "No individual titles yet.": "Noch keine Einzeltitel.",
    "No managers with registered net worth yet.": "Noch keine Manager mit registriertem Vermögen.",
    "No match clock": "Keine Spieluhr",
    "No matchdays": "Keine Spieltage",
    "No matches in the current season.": "Keine Spiele in der aktuellen Saison.",
    "No matches in {{month}}": "Keine Spiele im {{month}}",
    "No matches on matchday {{week}}": "Keine Spiele am Spieltag {{week}}",
    "No matches on this matchday": "Keine Spiele an diesem Spieltag",
    "No news.": "Keine Nachrichten.",
    "No one has listed players for sale": "Niemand hat Spieler zum Verkauf angeboten",
    "No players for these filters.": "Keine Spieler für diese Filter.",
    "No players in squad.": "Keine Spieler im Kader.",
    "No players in this list yet.": "Noch keine Spieler in dieser Liste.",
    "No proposals received": "Keine Vorschläge erhalten",
    "No proposals sent": "Keine Vorschläge gesendet",
    "No ranking data": "Keine Ranglistendaten",
    "No registered shareholders": "Keine registrierten Aktionäre",
    "No rumors": "Keine Gerüchte",
    "No scheduled matches.": "Keine geplanten Spiele.",
    "No scouting reports yet.": "Noch keine Scouting-Berichte.",
    "No scouts. Hire your first one.": "Keine Scouts. Verpflichte den ersten.",
    "No seasons recorded yet.": "Noch keine Saisons erfasst.",
    "No staff hired": "Kein Personal verpflichtet",
    "No standings": "Keine Tabelle",
    "No standings yet.": "Noch keine Tabelle.",
    "No standout result this matchday.": "Kein herausragendes Ergebnis an diesem Spieltag.",
    "No targets": "Keine Ziele",
    "No teams in this league yet.": "Noch keine Teams in dieser Liga.",
    "No trained plays": "Keine trainierten Spielzüge",
    "OFFER ACCEPTED": "ANGEBOT ANGENOMMEN",
    "OFFER REJECTED": "ANGEBOT ABGELEHNT",
    "OPEN": "OFFEN",
    "Offer sent": "Angebot gesendet",
    "Offer withdrawn": "Angebot zurückgezogen",
    "Offside trap": "Abseitsfalle",
    "Open FDF Today": "FDF Today öffnen",
    "Operation failed": "Operation fehlgeschlagen",
    "Operations center": "Operationszentrum",
    "Operations ready": "Betrieb bereit",
    "Optimal lineup": "Optimale Aufstellung",
    "Optimal lineup applied": "Optimale Aufstellung angewendet",
    "Optimal operation": "Optimaler Betrieb",
    "Organisation": "Organisation",
    "Outsourcing": "Outsourcing",
    "PENDING": "AUSSTEHEND",
    "Passing": "Passspiel",
    "Pay release clause": "Ausstiegsklausel zahlen",
    "Pending matches from the current matchday will be simulated. This action cannot be undone.": "Ausstehende Spiele des aktuellen Spieltags werden simuliert. Diese Aktion kann nicht rückgängig gemacht werden.",
    "Personality": "Persönlichkeit",
    "Plant rumor (−120 prestige)": "Gerücht streuen (−120 Prestige)",
    "Played": "Gespielt",
    "Player": "Spieler",
    "Player #{{id}}": "Spieler Nr. {{id}}",
    "Player promoted to first team!": "Spieler in den Profikader befördert!",
    "Player unavailable": "Spieler nicht verfügbar",
    "Players in form": "Spieler in Form",
    "Players in groups": "Spieler in Gruppen",
    "Players without a club will appear here.": "Spieler ohne Verein erscheinen hier.",
    "Players you're tracking. Automatically assigned to free scouts when available.": "Spieler, die du verfolgst. Automatisch freien Scouts zugewiesen, wenn verfügbar.",
    "Position": "Position",
    "Position {{pos}}": "Position {{pos}}",
    "Position {{pos}}, {{club}}": "Position {{pos}}, {{club}}",
    "Potential {{potential}} · value {{value}}": "Potenzial {{potential}} · Wert {{value}}",
    "Potential {{talent}}/99": "Potenzial {{talent}}/99",
    "Pre-season": "Vorsaison",
    "Prepare next turn": "Nächste Runde vorbereiten",
    "Preparing turn summary…": "Rundenzusammenfassung wird vorbereitet…",
    "Press conference pending": "Pressekonferenz ausstehend",
    "Prestige": "Prestige",
    "Prestige 2.0": "Prestige 2.0",
    "Previous": "Zurück",
    "Previous matchday": "Vorheriger Spieltag",
    "Previous month": "Vorheriger Monat",
    "Professional contract: {{name}}": "Profivertrag: {{name}}",
    "Profile": "Profil",
    "Progress to level {{level}}": "Fortschritt zu Level {{level}}",
    "Projection": "Projektion",
    "Promote": "Hochziehen",
    "Promotion failed": "Beförderung fehlgeschlagen",
    "Prospect": "Talent",
    "Prospect #{{id}}": "Talent Nr. {{id}}",
    "Prospects in development": "Talente in Entwicklung",
    "Purchased {{count}} shares": "{{count}} Aktien gekauft",
    "Quarter-finals": "Viertelfinale",
    "RIVAL OF THE WEEK": "RIVALE DER WOCHE",
    "Ranking has no data yet.": "Rangliste hat noch keine Daten.",
    "Rating": "Note",
    "Ready for full workload.": "Bereit für volle Belastung.",
    "Received": "Empfangen",
    "Recent matches": "Letzte Spiele",
    "Recommended: {{name}}": "Empfohlen: {{name}}",
    "Reject proposal": "Vorschlag ablehnen",
    "Reject this proposal? You won't be able to recover it.": "Diesen Vorschlag ablehnen? Du kannst ihn nicht wiederherstellen.",
    "Release clause": "Ausstiegsklausel",
    "Release clause:": "Ausstiegsklausel:",
    "Relegation zone": "Abstiegszone",
    "Relegation zone, position {{pos}}": "Abstiegszone, Position {{pos}}",
    "Reload": "Neu laden",
    "Remove": "Entfernen",
    "Remove from sale": "Vom Markt nehmen",
    "Remove from targets": "Aus Zielen entfernen",
    "Remove this player from the transfer market?": "Diesen Spieler vom Transfermarkt nehmen?",
    "Removed from sale": "Vom Markt genommen",
    "Renewal accepted": "Verlängerung angenommen",
    "Report advanced": "Bericht vertieft",
    "Reputation": "Reputation",
    "Required starting salary": "Erforderliches Startgehalt",
    "Retry": "Erneut versuchen",
    "Retry access": "Zugriff erneut versuchen",
    "Revenue": "Einnahmen",
    "Right": "Rechts",
    "Role": "Rolle",
    "Room layout": "Zimmerplan",
    "Round of 16": "Achtelfinale",
    "Round {{n}}": "Runde {{n}}",
    "Rumor planted in the press": "Gerücht in der Presse platziert",
    "Rumors": "Gerüchte",
    "SWITCH TO 2D": "AUF 2D UMSCHALTEN",
    "Salary offer": "Gehaltsangebot",
    "Scout": "Scout",
    "Scout #{{id}}": "Scout Nr. {{id}}",
    "Scout hired": "Scout verpflichtet",
    "Scouted players": "Gescoutete Spieler",
    "Scouting department": "Scouting-Abteilung",
    "Scouting mission created": "Scouting-Mission erstellt",
    "Scouting missions": "Scouting-Missionen",
    "Scouting zone": "Scouting-Zone",
    "Scouts": "Scouts",
    "Scout…": "Scout…",
    "Sealed bid #{{id}}": "Versiegeltes Gebot Nr. {{id}}",
    "Search": "Suchen",
    "Season": "Saison",
    "Season in progress": "Laufende Saison",
    "Sees exact rival bid valuations": "Sieht exakte Bewertungen rivalisierender Gebote",
    "Select another matchday in the top navigator.": "Wähle einen anderen Spieltag in der oberen Navigation.",
    "Semi-finals": "Halbfinale",
    "Send to scout": "Zum Scouting senden",
    "Sending…": "Senden…",
    "Sent": "Gesendet",
    "Server unavailable": "Server nicht verfügbar",
    "Set as Primary": "Als Haupt setzen",
    "Set-piece master": "Standardspezialist",
    "Settings": "Einstellungen",
    "Shares": "Aktien",
    "Shares required": "Erforderliche Aktien",
    "Shooting": "Schuss",
    "Sign": "Verpflichten",
    "Sign contract": "Vertrag unterschreiben",
    "Signing targets": "Verpflichtungsziele",
    "Simulate match": "Spiel simulieren",
    "Simulate now": "Jetzt simulieren",
    "Simulate this match now?": "Dieses Spiel jetzt simulieren?",
    "Simulate {{home}} vs {{away}}?": "{{home}} vs {{away}} simulieren?",
    "Skill points": "Skillpunkte",
    "Skill tree": "Skillbaum",
    "Skills": "Fähigkeiten",
    "Social card generated": "Social-Karte erstellt",
    "Sold {{count}} shares · {{proceeds}}": "{{count}} Aktien verkauft · {{proceeds}}",
    "Sow dressing room crisis": "Kabinenkrise säen",
    "Squad": "Kader",
    "Squad number": "Rückennummer",
    "Squad status": "Kaderstatus",
    "Squad unavailable": "Kader nicht verfügbar",
    "Stadium unavailable": "Stadion nicht verfügbar",
    "Stadium view": "Stadionansicht",
    "Staff member dismissed": "Mitarbeiter entlassen",
    "Staff structure": "Personalstruktur",
    "Standings": "Tabelle",
    "Standings: {{league}}": "Tabelle: {{league}}",
    "Start training a play so your team masters it in matches.": "Starte das Training eines Spielzugs, damit dein Team ihn im Spiel beherrscht.",
    "Starters": "Starter",
    "Statistics": "Statistiken",
    "Status: Unavailable": "Status: Nicht verfügbar",
    "Stop following this player?": "Diesen Spieler nicht mehr verfolgen?",
    "Style": "Stil",
    "Substitutes": "Ersatzspieler",
    "Suspended": "Gesperrt",
    "TRAINING…": "TRAINING…",
    "Table": "Tabelle",
    "Tackling": "Tackling",
    "Tactical genius": "Taktikgenie",
    "Tactics": "Taktik",
    "Tactics board, plays and match": "Taktikbrett, Spielzüge und Spiel",
    "Tactics saved successfully": "Taktik erfolgreich gespeichert",
    "Tactics set as primary": "Taktik als Haupt gesetzt",
    "Target": "Ziel",
    "Target club": "Zielverein",
    "Target club…": "Zielverein…",
    "Team personnel management": "Teampersonalmanagement",
    "Team shares": "Vereinsaktien",
    "Team talk applied": "Mannschaftsansprache angewendet",
    "Technical talk": "Technische Ansprache",
    "Technology upgrade approval": "Genehmigung des Technologie-Upgrades",
    "Tension": "Spannung",
    "The FDF world has taken another step.": "Die FDF-Welt hat einen weiteren Schritt gemacht.",
    "The Matchday": "Der Spieltag",
    "The club is up to date. Check the front page and prepare for the next match.": "Der Verein ist auf dem neuesten Stand. Titelseite prüfen und nächstes Spiel vorbereiten.",
    "The financial module has not returned data yet.": "Das Finanzmodul hat noch keine Daten geliefert.",
    "The lit floor marks your academy's tech progress. Each level raises youth players' base average.": "Die beleuchtete Etage markiert den Tech-Fortschritt deiner Akademie. Jedes Level erhöht den Basisdurchschnitt der Jugendspieler.",
    "The market is very quiet this week.": "Der Markt ist diese Woche sehr ruhig.",
    "The matchday event": "Das Spieltagsereignis",
    "The numbers tell the project's story: cash, wage bill and outlook. This isn't a BI dashboard — it's the report the sports press would read.": "Die Zahlen erzählen die Projektgeschichte: Kasse, Gehaltsmasse und Ausblick. Kein BI-Dashboard — der Bericht, den die Sportpresse lesen würde.",
    "The player rejects the renewal.": "Der Spieler lehnt die Verlängerung ab.",
    "The player will reject this offer.": "Der Spieler wird dieses Angebot ablehnen.",
    "Third kit": "Drittes Trikot",
    "This will hide your tactics from rivals for 3 turns, but will use one directive charge.": "Dies verbirgt deine Taktik 3 Runden vor Rivalen, verbraucht aber eine Direktiven-Ladung.",
    "Tickets": "Tickets",
    "Today's front page is ready at your club.": "Die heutige Titelseite ist in deinem Verein bereit.",
    "Tomorrow's headlines": "Schlagzeilen von morgen",
    "Top scorers": "Torschützen",
    "Total recorded change": "Gesamte erfasste Veränderung",
    "Total staff": "Gesamtpersonal",
    "Tournament": "Turnier",
    "Train": "Trainieren",
    "Trained plays": "Trainierte Spielzüge",
    "Training": "Training",
    "Training center": "Trainingszentrum",
    "Training closed": "Training geschlossen",
    "Training «{{type}}»": "Training «{{type}}»",
    "Training...": "Training…",
    "Transfer market": "Transfermarkt",
    "Transfer window": "Transferfenster",
    "Transfers": "Transfers",
    "Turn {{turn}}": "Runde {{turn}}",
    "Turn {{turn}}. Close training (3t) or give a home team talk (2t). Directive cost after use 2.": "Runde {{turn}}. Training schließen (3r) oder Heim-Mannschaftsansprache halten (2r). Direktivenkosten nach Nutzung 2.",
    "U19 squad": "U19-Kader",
    "Under construction": "Im Bau",
    "Unique roles": "Einzigartige Rollen",
    "Unlock": "Freischalten",
    "Upcoming Matches": "Kommende Spiele",
    "Upgrade": "Upgraden",
    "Upgrade failed (insufficient funds?)": "Upgrade fehlgeschlagen (unzureichende Mittel?)",
    "Upgrade technology": "Technologie upgraden",
    "Upgrades and expansions": "Upgrades und Erweiterungen",
    "Use \"Propose transfer\" to open formal negotiations with another club.": "Nutze „Transfer vorschlagen“, um formelle Verhandlungen mit einem anderen Verein zu eröffnen.",
    "VIEW IN 3D": "IN 3D ANSEHEN",
    "VIEW PORTRAIT": "PORTRAIT ANSEHEN",
    "Value": "Wert",
    "View match": "Spiel ansehen",
    "View offers and vacancies →": "Angebote und Stellen →",
    "Vote for the community's most spectacular play and leave your mark on the chronicle.": "Stimme für die spektakulärste Aktion der Community und hinterlasse deine Spur in der Chronik.",
    "Voting open": "Abstimmung offen",
    "W": "S",
    "WEEK {{week}}": "WOCHE {{week}}",
    "WINDOW": "FENSTER",
    "Wage": "Gehalt",
    "Wage/mo": "Gehalt/Mo.",
    "Weekly missions": "Wöchentliche Missionen",
    "While you were away": "Während du weg warst",
    "Will boost morale and performance in the next home match, using one directive charge.": "Steigert Moral und Leistung im nächsten Heimspiel und verbraucht eine Direktiven-Ladung.",
    "Window closed: the server will reject it.": "Fenster geschlossen: der Server lehnt ab.",
    "Withdraw offer": "Angebot zurückziehen",
    "Withdraw player": "Spieler zurückziehen",
    "Withdraw this offer from the market? You won't be able to recover it.": "Dieses Angebot vom Markt zurückziehen? Du kannst es nicht wiederherstellen.",
    "Work in progress": "In Arbeit",
    "Years (1-5)": "Jahre (1-5)",
    "Years remaining": "Verbleibende Jahre",
    "Yes, close": "Ja, schließen",
    "Yes, give team talk": "Ja, Mannschaftsansprache halten",
    "You": "Du",
    "You dropped {{count}} place": "Du bist {{count}} Platz abgerutscht",
    "You dropped {{count}} places": "Du bist {{count}} Plätze abgerutscht",
    "You have no staff hired right now. Use «Hire Staff» to sign candidates.": "Du hast derzeit kein Personal. Nutze „Personal verpflichten“, um Kandidaten zu unterzeichnen.",
    "You only have {{owned}} shares": "Du hast nur {{owned}} Aktien",
    "You rose {{count}} place": "Du bist {{count}} Platz aufgestiegen",
    "You rose {{count}} places": "Du bist {{count}} Plätze aufgestiegen",
    "You will pay {{amount}} for {{player}}'s release clause. This operation is irrevocable.": "Du zahlst {{amount}} für die Ausstiegsklausel von {{player}}. Dieser Vorgang ist unwiderruflich.",
    "You will spend 120 prestige points to sow discord in the rival dressing room. Maximum 1 per week.": "Du gibst 120 Prestigepunkte aus, um Zwietracht in der rivalisierenden Kabine zu säen. Maximal 1 pro Woche.",
    "Your bid": "Dein Gebot",
    "Your bid must exceed the current one.": "Dein Gebot muss das aktuelle übersteigen.",
    "Your match is still sealed. Open it whenever you want.": "Dein Spiel ist noch versiegelt. Öffne es, wann du willst.",
    "Your matches": "Deine Spiele",
    "Your squad, face to face": "Dein Kader, von Angesicht zu Angesicht",
    "Your streak:": "Deine Serie:",
    "Your transfer offers will appear here.": "Deine Transferangebote erscheinen hier.",
    "Zone…": "Zone…",
    "attribute pts": "Attribut-Pkt.",
    "avg. rating": "Ø-Note",
    "dormitory expansion (+10 slots)": "Schlafsaal-Erweiterung (+10 Plätze)",
    "facility upgrade (Level +1)": "Anlagen-Upgrade (Level +1)",
    "months remaining": "Monate verbleibend",
    "occupancy": "Auslastung",
    "of {{max}}": "von {{max}}",
    "scout": "Scout",
    "sealed": "versiegelt",
    "slots": "Plätze",
    "the manager indicator": "der Manager-Indikator",
    "until {{date}}": "bis {{date}}",
    "{{active}}/{{max}} in match": "{{active}}/{{max}} im Spiel",
    "{{club}} offers {{amount}}": "{{club}} bietet {{amount}}",
    "{{count}} active module": "{{count}} aktives Modul",
    "{{count}} active modules": "{{count}} aktive Module",
    "{{count}} market offer": "{{count}} Marktangebot",
    "{{count}} market offers": "{{count}} Marktangebote",
    "{{count}} matches": "{{count}} Spiele",
    "{{count}} pl.": "{{count}} Sp.",
    "{{count}} unread message": "{{count}} ungelesene Nachricht",
    "{{count}} unread messages": "{{count}} ungelesene Nachrichten",
    "{{count}} years": "{{count}} Jahre",
    "{{count}} youth player ready to promote": "{{count}} Jugendspieler bereit zur Beförderung",
    "{{count}} youth players ready to promote": "{{count}} Jugendspieler bereit zur Beförderung",
    "{{fee}} signing fee": "{{fee}} Handgeld",
    "{{name}} cannot play (injury/suspension)": "{{name}} kann nicht spielen (Verletzung/Sperre)",
    "{{name}} hired": "{{name}} verpflichtet",
    "{{name}} leads the front page with rating {{rating}}.": "{{name}} führt die Titelseite mit Note {{rating}}.",
    "{{name}} played their match:": "{{name}} hat sein Spiel absolviert:",
    "{{occupied}} / {{capacity}} occupied": "{{occupied}} / {{capacity}} belegt",
    "{{player}} is yours via release clause!": "{{player}} ist dein via Ausstiegsklausel!",
    "{{player}} loaned to {{club}}": "{{player}} an {{club}} verliehen",
    "{{player}} signs for {{years}} years": "{{player}} unterschreibt für {{years}} Jahre",
    "· Base average = residence level × 3 + random(−5..25) − random(0..residences) + 13 + location value (1-20). Capped between 20 and 75.": "· Basisdurchschnitt = Residenz-Level × 3 + Zufall(−5..25) − Zufall(0..Residenzen) + 13 + Standortwert (1-20). Begrenzt auf 20 bis 75.",
    "· Each attribute = average − 50 + random(0..30) − position penalty.": "· Jedes Attribut = Durchschnitt − 50 + Zufall(0..30) − Positionsmalus.",
    "· Every ~3 in-game months, one player graduates per residence (you can choose their position).": "· Alle ~3 Spielmonate kommt ein Spieler pro Residenz (Position wählbar).",
    "· Global annual limit: 3 players with 7 bars and 21 with 6 bars. Retired icons add a bonus.": "· Jährliches Weltlimit: 3 Spieler mit 7 Balken und 21 mit 6 Balken. Ausgeschiedene Ikonen geben Bonus.",
    "· Talent (ceiling) = attribute + 50 + random(0..15). The sports city raises the range (without it 15-60; level 8: 43-84).": "· Talent (Decke) = Attribut + 50 + Zufall(0..15). Sportstadt erhöht Spanne (ohne 15-60; Level 8: 43-84).",
    "· closed": "· geschlossen",
    "· played": "· gespielt",
    "· {{count}} point available": "· {{count}} Punkt verfügbar",
    "· {{count}} points available": "· {{count}} Punkte verfügbar",
    "€150,000": "150.000 €",
    "€250,000": "250.000 €",
    "/mo": "/Mo.",
    "⇄ {{in}} on for {{out}}": "⇄ {{in}} für {{out}}",
    "⚠️ Requires recovery protocol.": "⚠️ Erfordert Erholungsprotokoll.",
    "🏥 Injured": "🏥 Verletzt",
    "🟥 Suspended": "🟥 Gesperrt",
}

# IT glossary - continue in part 2 due to size; for now write what we have and generate file
IT_GLOSSARY: dict[str, str] = {}

def main():
    en_strings = load_en_strings()
    # Fill IT from separate chunk file if exists
    it_chunk = SCRIPTS / "gameplay_i18n_it_glossary.json"
    if it_chunk.exists():
        IT_GLOSSARY.update(json.loads(it_chunk.read_text(encoding="utf-8")))

    de = {}
    it = {}
    missing_de = []
    missing_it = []
    for en in en_strings:
        if en in KEEP:
            de[en] = en
            it[en] = en
        elif en in DE_GLOSSARY:
            de[en] = DE_GLOSSARY[en]
        else:
            de[en] = en
            missing_de.append(en)
        if en in IT_GLOSSARY:
            it[en] = IT_GLOSSARY[en]
        elif en in KEEP:
            pass
        else:
            it[en] = en
            missing_it.append(en)

    out = {"de": de, "it": it}
    (SCRIPTS / "gameplay-i18n-de-it-overrides.json").write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"DE: {len(de)} entries, missing {len(missing_de)}")
    print(f"IT: {len(it)} entries, missing {len(missing_it)}")
    if missing_de:
        print("DE missing:", missing_de[:5])
    if missing_it:
        print("IT missing:", missing_it[:5])

if __name__ == "__main__":
    main()
