#!/usr/bin/env python3
"""Build IT glossary from FR glossary + FR->IT football term map."""
from __future__ import annotations

import json
import re
from pathlib import Path

from gameplay_i18n_engine import FR_GLOSSARY, KEEP, TOKEN_RE

SCRIPTS = Path(__file__).resolve().parent


def protect(text: str) -> tuple[str, list[str]]:
    tokens: list[str] = []

    def repl(m: re.Match[str]) -> str:
        tokens.append(m.group(0))
        return f"\x00{len(tokens) - 1}\x00"

    return TOKEN_RE.sub(repl, text), tokens


def restore(text: str, tokens: list[str]) -> str:
    for i, t in enumerate(tokens):
        text = text.replace(f"\x00{i}\x00", t)
    return text


# FR -> IT phrase map (longest first at apply time)
FR_TO_IT: dict[str, str] = {
    " · non enregistré": " · non salvato",
    "+ Nouveau": "+ Nuovo",
    "+ Niveau académie (meilleures stats de base)": "+ Livello accademia (statistiche base migliori)",
    "+1 rapport adversaire par journée": "+1 rapporto avversario per giornata",
    "+1 remplacement programmé (4 règles)": "+1 sostituzione programmata (4 regole)",
    "+1 discours d'équipe par saison": "+1 discorso di squadra per stagione",
    "+10 places pour nouveaux espoirs": "+10 posti per nuovi talenti",
    "+2 actions actives par match (10)": "+2 azioni attive per partita (10)",
    "+5 % droits à l'image": "+5 % diritti d'immagine",
    "3D indisponible dans ce navigateur — portrait affiché.": "3D non disponibile in questo browser — ritratto mostrato.",
    "Un entraîneur ne peut avoir que 6 joueurs assignés": "Un allenatore può avere solo 6 giocatori assegnati",
    "DISCOURS ACTIF (jusqu'à T{{turn}})": "DISCORSO ATTIVO (fino a T{{turn}})",
    "RAFRAÎCHISSEMENT AUTO": "AGGIORNAMENTO AUTO",
    "DISPONIBLE": "DISPONIBILE",
    "ADJUDICÉ": "AGGIUDICATO",
    "ADJUDICÉ À VOUS": "AGGIUDICATO A TE",
    "Académie": "Accademia",
    "Académie & centre de formation": "Accademia & settore giovanile",
    "Académie fermée": "Accademia chiusa",
    "Accepter cette proposition de transfert ? Le mouvement sera exécuté de façon irréversible.": "Accettare questa proposta di trasferimento? Il movimento sarà eseguito in modo irreversibile.",
    "Accepter le transfert": "Accettare il trasferimento",
    "Les négociations acceptées ou refusées apparaîtront ici.": "Le trattative accettate o rifiutate appariranno qui.",
    "Succès": "Obiettivi",
    "Succès ({{count}})": "Obiettivi ({{count}})",
    "Décision": "Decisione",
    "Activer pour le match": "Attiva per la partita",
    "Actives": "Attive",
    "Ajouté aux objectifs et recruteur assigné.": "Aggiunto agli obiettivi e osservatore assegnato.",
    "Avancer la journée": "Avanza giornata",
    "Approfondir le rapport": "Approfondisci rapporto",
    "Avancés": "Avanzate",
    "Tableau tactique avancé": "Lavagna tattica avanzata",
    "Âge": "Età",
    "Exigences de l'agent": "Richieste dell'agente",
    "Les agents acceptent 5 % de salaire en moins": "Gli agenti accettano il 5 % in meno di stipendio",
    "Toutes": "Tutte",
    "Motive aussi les joueurs similaires en août": "Motiva anche giocatori simili ad agosto",
    "Une pénalité de 8 % s'appliquera pour chaque année restante. Confirmer la résiliation ?": "Si applicherà una penalità dell'8 % per ogni anno rimanente. Confermare la rescissione?",
    "Analyse": "Analisi",
    "Salaire annuel": "Stipendio annuale",
    "Niveau architectural": "Livello architettonico",
    "Amélioration architecturale terminée": "Miglioramento architettonico completato",
    "Résident assigné": "Residente assegnato",
    "Assistants": "Assistenti",
    "Passes déc.": "Assist",
    "PD": "Assist",
    "Affluence": "Presenze",
    "Bonus d'affluence": "Bonus presenze",
    "Enchères indisponibles": "Aste non disponibili",
    "Autoriser les fonds": "Autorizza fondi",
    "Disponible": "Disponibile",
    "Disponible le : {{date}}": "Disponibile il: {{date}}",
    "Chambre disponible": "Stanza disponibile",
    "Moyenne": "Media",
    "Forme moyenne": "Forma media",
    "Moral moyen": "Morale media",
    "Ext.": "Tr.",
    "Maillot extérieur": "Maglia away",
    "Staff technique": "Staff tecnico",
    "Bandeau copié dans le presse-papiers !": "Banner copiato negli appunti!",
    "Talent de base": "Talento base",
    "Soyez le premier à obtenir un paquet d'actions.": "Sii il primo a ottenere un pacchetto di azioni.",
    "Meilleure note moyenne": "Miglior voto medio",
    "Enchérir": "Offri",
    "Montant de l'offre (€)": "Importo dell'offerta (€)",
    "Offre envoyée": "Offerta inviata",
    "Enchérir {{amount}} pour {{player}} ? Le montant restera scellé jusqu'à la clôture.": "Offrire {{amount}} per {{player}}? L'importo resterà sigillato fino alla chiusura.",
    "Objectif du conseil : {{objective}}": "Obiettivo del consiglio: {{objective}}",
    "Commercial né": "Venditore nato",
    "Tableau": "Tabellone",
    "Rompre": "Interrompi",
    "Rompre le contrat": "Rescindi contratto",
    "Rompre le contrat d'image": "Rescindi contratto immagine",
    "Rompre les négociations": "Interrompi trattative",
    "Construire": "Costruisci",
    "TOTAL CARRIÈRE": "TOTALE CARRIERA",
    "FERMÉ": "CHIUSO",
    "FERMÉ (jusqu'à T{{turn}})": "CHIUSO (fino a T{{turn}})",
    "TERMINÉE": "COMPLETATA",
    "Calcul en cours…": "Calcolo in corso…",
    "Calendrier": "Calendario",
    "Vue calendrier": "Vista calendario",
    "Sérénité": "Serenità",
    "Installations du campus": "Strutture del campus",
    "Annuler la sous-traitance": "Annulla outsourcing",
    "Annuler le service": "Annulla servizio",
    "Annuler {{name}} ? Vous cesserez de payer le coût mensuel.": "Annullare {{name}}? Smetterai di pagare il costo mensile.",
    "Capacité": "Capacità",
    "Parcours": "Percorso",
    "Caisse": "Cassa",
    "Catégories couvertes": "Categorie coperte",
    "Zone Ligue des champions, position {{pos}}": "Zona Champions League, posizione {{pos}}",
    "Choisissez une autre compétition ou attendez le prochain tour.": "Scegli un'altra competizione o attendi il prossimo turno.",
    "Choisissez club et joueur.": "Scegli club e giocatore.",
    "Fermer l'entraînement ({{uses}}/2)": "Chiudi allenamento ({{uses}}/2)",
    "Fermer l'entraînement": "Chiudi allenamento",
    "Fermer l'entraînement à huis clos ?": "Chiudere l'allenamento a porte chiuse?",
    "Fermées": "Chiuse",
    "Rapport financier du club": "Report finanziario del club",
    "Profil du club": "Profilo del club",
    "Entraîneur licencié": "Allenatore licenziato",
    "Entraîneur recruté": "Allenatore ingaggiato",
    "Entraîneur introuvable": "Allenatore non trovato",
    "Entraîneur de {{club}}": "Allenatore di {{club}}",
    "Entraîneurs": "Allenatori",
    "Collecte des événements récents…": "Raccolta eventi recenti…",
    "Compétition indisponible": "Competizione non disponibile",
    "Compétitions": "Competizioni",
    "Confirmer l'offre": "Conferma offerta",
    "Confirmer l'autorisation du conseil d'investir {{amount}} dans {{project}} ?": "Confermare l'autorizzazione del consiglio a investire {{amount}} in {{project}}?",
    "Confirmer le licenciement ? L'indemnité correspondante s'appliquera.": "Confermare il licenziamento? Si applicherà l'indennità corrispondente.",
    "Confirmer le prêt": "Conferma prestito",
    "Confirmer le paiement": "Conferma pagamento",
    "Confirmer le paiement de la clause libératoire": "Conferma pagamento clausola rescissoria",
    "Confirmer l'achat d'actions ?": "Confermare l'acquisto di azioni?",
    "Confirmer la vente d'actions ?": "Confermare la vendita di azioni?",
    "Continuer vers le tableau de bord": "Continua alla dashboard",
    "Contrat": "Contratto",
    "Fin de contrat": "Fine contratto",
    "Contrats": "Contratti",
    "Corner": "Calcio d'angolo",
    "Impossible d'enchérir": "Impossibile fare un'offerta",
    "Impossible de créer la tactique": "Impossibile creare la tattica",
    "Impossible de suivre le joueur.": "Impossibile seguire il giocatore.",
    "Impossible de charger le centre de formation": "Impossibile caricare il settore giovanile",
    "Impossible de charger le staff technique": "Impossibile caricare lo staff tecnico",
    "Impossible de charger le calendrier": "Impossibile caricare il calendario",
    "Impossible de charger la carrière": "Impossibile caricare la carriera",
    "Impossible de charger la compétition": "Impossibile caricare la competizione",
    "Impossible de charger les compétitions": "Impossibile caricare le competizioni",
    "Impossible de charger les maillots": "Impossibile caricare le maglie",
    "Impossible de charger le mercato": "Impossibile caricare il mercato",
    "Impossible de charger les matchs": "Impossibile caricare le partite",
    "Impossible de charger le joueur": "Impossibile caricare il giocatore",
    "Impossible de charger les actions": "Impossibile caricare le azioni",
    "Impossible de charger le recrutement": "Impossibile caricare lo scouting",
    "Impossible de charger l'effectif": "Impossibile caricare la rosa",
    "Impossible de charger le classement": "Impossibile caricare la classifica",
    "Impossible de charger la tactique": "Impossibile caricare la tattica",
    "Impossible de charger la liste d'objectifs": "Impossibile caricare la lista obiettivi",
    "Impossible de charger l'entraînement": "Impossibile caricare l'allenamento",
    "Impossible d'effectuer le changement": "Impossibile effettuare il cambio",
    "Impossible de lire la date in-game du serveur ; utilisez la vue liste par journées.": "Impossibile leggere la data in-game dal server; usa la vista lista per giornate.",
    "Impossible de renouveler.": "Impossibile rinnovare.",
    "Impossible de revoir le match": "Impossibile rivedere la partita",
    "Impossible d'enregistrer le schéma": "Impossibile salvare lo schema",
    "Impossible d'enregistrer le milieu": "Impossibile salvare il centrocampo",
    "Impossible d'enregistrer la tactique": "Impossibile salvare la tattica",
    "Impossible de définir comme principale": "Impossibile impostare come principale",
    "Impossible de partager le match": "Impossibile condividere la partita",
    "Impossible de lancer les travaux": "Impossibile avviare i lavori",
    "Impossible de lancer l'action": "Impossibile avviare l'azione",
    "Impossible d'activer/désactiver l'action": "Impossibile attivare/disattivare l'azione",
    "Impossible de débloquer": "Impossibile sbloccare",
    "Contre-attaque": "Contropiede",
    "Pays": "Paese",
    "Banc actuel": "Panchina attuale",
    "Niveau actuel": "Livello attuale",
    "Résidents actuels": "Residenti attuali",
    "DERBY": "DERBY",
    "Quotidien": "Giornaliero",
    "Date": "Data",
    "Désactiver": "Disattiva",
    "Démenti publié": "Smentita pubblicata",
    "Derby": "Derby",
    "Schéma enregistré": "Schema salvato",
    "Club de destination": "Club di destinazione",
    "Progression": "Progressione",
    "Arbre de développement": "Albero di sviluppo",
    "Coup franc direct": "Calcio di punizione diretto",
    "Rival direct": "Rivale diretto",
    "Bureau du directeur sportif": "Ufficio del direttore sportivo",
    "Licencier": "Licenzia",
    "Licencier un membre du staff": "Licenzia membro dello staff",
    "Glisser pour pivoter · molette pour zoomer": "Trascina per ruotare · rotella per zoom",
    "Vestiaire": "Spogliatoio",
    "Gestion du vestiaire et du moral": "Gestione spogliatoio e morale",
    "Leader du vestiaire": "Leader dello spogliatoio",
    "Dribble": "Dribbling",
    "Durée (années)": "Durata (anni)",
    "Économie et négociation": "Economia e negoziazione",
    "Résumé économique": "Riepilogo economia",
    "Économie indisponible": "Economia non disponibile",
    "Psychologue d'élite": "Psicologo d'élite",
    "Effectif vide": "Rosa vuota",
    "Erreur lors de l'avancement de la journée : {{msg}}": "Errore nell'avanzamento della giornata: {{msg}}",
    "Erreur lors du licenciement.": "Errore nel licenziamento.",
    "Erreur lors du recrutement. Vérifiez votre budget.": "Errore nell'ingaggio. Controlla il budget.",
    "Erreur lors du chargement des actions": "Errore nel caricamento delle azioni",
    "Erreur lors de la simulation : {{msg}}": "Errore nella simulazione: {{msg}}",
    "Euphorie": "Euforia",
    "Zone Ligue Europa, position {{pos}}": "Zona Europa League, posizione {{pos}}",
    "Résumé des événements depuis votre dernière session ({{since}}).": "Riepilogo eventi dalla tua ultima sessione ({{since}}).",
    "Agrandir les dortoirs": "Amplia dormitori",
    "Extension": "Ampliamento",
    "Approbation du plan d'extension": "Approvazione piano di ampliamento",
    "Expérience": "Esperienza",
    "Complexe sportif FDF": "Complesso sportivo FDF",
    "Archives FDF : génération de talents": "Archivi FDF: generazione talenti",
    "Les installations sont vides. Les recruteurs cherchent des talents.": "Le strutture sono vuote. Gli osservatori cercano talenti.",
    "État des installations": "Stato strutture",
    "Échec du calcul de la composition optimale": "Calcolo formazione ottimale fallito",
    "Échec de l'enregistrement de la tactique : {{msg}}": "Salvataggio tattica fallito: {{msg}}",
    "Ambiance des supporters": "Umore dei tifosi",
    "Match à la une": "Partita in evidenza",
    "Moins de filtres": "Meno filtri",
    "Roi des finances": "Re delle finanze",
    "Finition": "Finalizzazione",
    "Équipe première": "Prima squadra",
    "Rapport physique": "Report fisico",
    "Forme {{fitness}} % · Musculaire {{muscular}} %.": "Forma {{fitness}}% · Muscolare {{muscular}}%.",
    "Suivre": "Segui",
    "Abonné…": "Seguito…",
    "Pied": "Piede",
    "À vendre": "In vendita",
    "Pour {{player}}": "Per {{player}}",
    "Agent libre": "Svincolato",
    "Libre": "Libero",
    "Agent libre — signature directe sans indemnité (compte dans le plafond salarial) :": "Svincolato — firma diretta senza indennità (conta nel tetto salariale):",
    "Agents libres": "Svincolati",
    "Une": "Prima pagina",
    "Une copiée dans le presse-papiers !": "Prima pagina copiata negli appunti!",
    "Fiche complète →": "Scheda completa →",
    "BC": "GS",
    "DG": "DG",
    "MJ": "PG",
    "Apprenez à connaître chaque joueur avant de choisir le onze. La vue vestiaire est votre référence ; le tableau sert à l'analyse froide.": "Conosci ogni giocatore prima di schierare l'undici. La vista spogliatoio è il riferimento; la tabella serve per l'analisi fredda.",
    "Donner un discours ({{uses}}/2)": "Fai un discorso ({{uses}}/2)",
    "Donner un discours motivationnel à l'équipe à domicile ?": "Fare un discorso motivazionale alla squadra di casa?",
    "Discours à domicile": "Discorso in casa",
    "Aller": "Vai",
    "Aller au mercato": "Vai al mercato",
    "Aller au centre du match": "Vai al centro partita",
    "Aller au but de la semaine": "Vai al gol della settimana",
    "Allez à la recherche ou à l'effectif d'un autre club et cliquez sur « Suivre » sur un joueur.": "Vai alla ricerca o alla rosa di un altro club e clicca « Segui » su un giocatore.",
    "But": "Gol",
    "But de la semaine": "Gol della settimana",
    "Gardien": "Portiere",
    "Buts": "Gol",
    "Les buts tombent": "I gol stanno arrivando",
    "N'a pas encore joué.": "Non ha ancora giocato.",
    "Recruter": "Ingaggia",
    "Recrutez un recruteur pour créer des missions.": "Ingaggia un osservatore per creare missioni.",
    "Recrutez des entraîneurs par catégorie pour améliorer vos joueurs à chaque séance.": "Ingaggia allenatori per categoria per migliorare i giocatori a ogni sessione.",
    "Sous-traiter": "Outsourcing",
    "Recruter {{name}} pour {{cost}}/mois ?": "Ingaggiare {{name}} per {{cost}}/mese?",
    "Historique": "Storico",
    "Dom.": "Casa",
    "Maillot domicile": "Maglia home",
    "Palmarès": "Palmarès",
    "Lignes chaudes, clauses et rumeurs sur le bureau du directeur. L'avenir de l'effectif se décide ici — avec l'horloge du mercato toujours en marche.": "Linee calde, clausole e voci sulla scrivania del direttore. Il futuro della rosa si decide qui — con l'orologio del mercato sempre in ticchettio.",
    "EN JEU": "IN GIOCO",
    "Droits à l'image": "Diritti d'immagine",
    "Paiement immédiat et irrévocable.": "Pagamento immediato e irrevocabile.",
    "En cours": "In corso",
    "Date in-game : {{date}}": "Data in-game: {{date}}",
    "Recruteur interne": "Osservatore interno",
    "Blessé": "Infortunato",
    "Infirmerie et suspensions": "Infermeria e squalifiche",
    "Capacité installée": "Capacità installata",
    "Solde insuffisant pour cet achat": "Saldo insufficiente per questo acquisto",
    "Montant non valide.": "Importo non valido.",
    "Compétition non valide": "Competizione non valida",
    "Montant de contre-offre non valide.": "Importo controfferta non valido.",
    "Investir": "Investi",
    "Investissez les fonds du club pour agrandir les installations et améliorer la qualité de l'entraînement des jeunes.": "Investi i fondi del club per ampliare le strutture e migliorare la qualità dell'allenamento giovanile.",
    "Éliminatoire": "Eliminatoria",
    "Phases éliminatoires pas encore tirées au sort": "Fasi eliminatorie non ancora sorteggiate",
    "Les confrontations éliminatoires apparaîtront une fois le tirage effectué.": "Gli scontri eliminatori appariranno dopo il sorteggio.",
    "NIVEAU {{level}}": "LIVELLO {{level}}",
    "EN DIRECT": "IN DIRETTA",
    "PRÊTS": "PRESTITI",
    "Dernières actualités": "Ultime notizie",
    "Championnat": "Campionato",
    "Phase ligue": "Fase campionato",
    "Phase ligue (36)": "Fase campionato (36)",
    "Classement du championnat": "Classifica campionato",
    "Gaucher": "Mancino",
    "Niveau": "Livello",
    "Niveau {{level}}": "Livello {{level}}",
    "Mettez en vente depuis votre effectif.": "Metti in vendita dalla tua rosa.",
    "En direct": "In diretta",
    "Journée en direct": "Giornata in diretta",
    "Enchères en direct": "Aste in diretta",
    "Chargement des informations du stade…": "Caricamento informazioni stadio…",
    "Chargement du tableau tactique…": "Caricamento lavagna tattica…",
    "Prêter un joueur": "Presta giocatore",
    "Prêter {{player}} à {{club}} ? Le club de destination assumera le salaire jusqu'à la fin de saison.": "Prestare {{player}} a {{club}}? Il club di destinazione coprirà lo stipendio fino a fine stagione.",
    "Joueurs prêtés": "Giocatori in prestito",
    "Prêts": "Prestiti",
    "MAXIMUM": "MASSIMO",
    "MON EFFECTIF": "LA MIA ROSA",
    "Carrière du manager": "Carriera manager",
    "Classement des managers": "Classifica manager",
    "Mercato": "Mercato",
    "Infos mercato": "Info mercato",
    "Requin du mercato": "Squalo del mercato",
    "Valeur marchande": "Valore di mercato",
    "Match": "Partita",
    "Lien du match copié dans le presse-papiers": "Link partita copiato negli appunti",
    "Match introuvable": "Partita non trovata",
    "Journée traitée — {{count}} match(s) joué(s)": "Giornata elaborata — {{count}} partita/e giocata/e",
    "Journée {{n}}": "Giornata {{n}}",
    "Journée {{week}}": "Giornata {{week}}",
    "Journées": "Giornate",
    "Âge max": "Età max",
    "Valeur max (€)": "Valore max (€)",
    "Maximum": "Massimo",
    "Maximum {{max}} actions actives par match (règle FDF). Désactivez-en une autre d'abord.": "Massimo {{max}} azioni attive per partita (regola FDF). Disattivane un'altra prima.",
    "Âge min": "Età min",
    "Moyenne min": "Media min",
    "Dribble min": "Dribbling min",
    "Passe min": "Passaggio min",
    "Potentiel min": "Potenziale min",
    "Tir min": "Tiro min",
    "Tacle min": "Contrasto min",
    "Salaires mensuels": "Stipendi mensili",
    "Le moral baisse plus lentement après les défaites": "Il morale scende più lentamente dopo le sconfitte",
    "Motivateur": "Motivatore",
    "Démarquage": "Movimentazione",
    "Multijoueur": "Multigiocatore",
    "Indispensable": "Indispensabile",
    "Ma carrière": "La mia carriera",
    "Mes matchs": "Le mie partite",
    "Mes offres": "Le mie offerte",
    "NOUVELLE OFFRE": "NUOVA OFFERTA",
    "PROCHAIN MATCH": "PROSSIMA PARTITA",
    "PAS À VENDRE": "NON IN VENDITA",
    "Banc NPC": "Panchina NPC",
    "Nom": "Nome",
    "Naviguez avec ‹ › ou appuyez sur AUJOURD'HUI pour revenir à la date actuelle.": "Naviga con ‹ › o premi OGGI per tornare alla data attuale.",
    "Négocier le recrutement": "Negozia ingaggio",
    "Négociations": "Trattative",
    "Négociations indisponibles": "Trattative non disponibili",
    "Négociateur": "Negoziatore",
    "Patrimoine": "Patrimonio",
    "Nouvelle action": "Nuova azione",
    "Actualité": "Notizia",
    "Suivant": "Successivo",
    "Journée suivante": "Giornata successiva",
    "Mois suivant": "Mese successivo",
    "Aucun succès pour l'instant. Votre premier titre vous attend.": "Nessun obiettivo ancora. Il tuo primo titolo ti aspetta.",
    "Aucune enchère active pour le moment. Créez-en une depuis un joueur en vente sur le mercato.": "Nessuna asta attiva al momento. Creane una da un giocatore in vendita sul mercato.",
    "Aucune offre active": "Nessuna offerta attiva",
    "Aucune enchère": "Nessuna asta",
    "Aucune enchère dans ce filtre.": "Nessuna asta in questo filtro.",
    "Aucun staff technique": "Nessuno staff tecnico",
    "Aucune offre pour l'instant. Soyez le premier !": "Nessuna offerta al momento. Sii il primo!",
    "Aucun tableau disponible": "Nessun tabellone disponibile",
    "Aucune donnée de carrière": "Nessun dato carriera",
    "Sans club": "Senza club",
    "Aucune donnée.": "Nessun dato.",
    "Pas encore d'historique de développement — la courbe progresse avec l'entraînement et les minutes.": "Nessuno storico di sviluppo — la curva cresce con allenamento e minuti.",
    "Aucun agent libre": "Nessuno svincolato",
    "Aucun historique": "Nessuno storico",
    "Aucun titre individuel pour l'instant.": "Nessun titolo individuale ancora.",
    "Aucun manager avec patrimoine enregistré pour l'instant.": "Nessun manager con patrimonio registrato ancora.",
    "Aucune horloge de match": "Nessun orologio partita",
    "Aucune journée": "Nessuna giornata",
    "Aucun match cette saison.": "Nessuna partita in questa stagione.",
    "Aucun match en {{month}}": "Nessuna partita a {{month}}",
    "Aucun match à la journée {{week}}": "Nessuna partita alla giornata {{week}}",
    "Aucun match cette journée": "Nessuna partita in questa giornata",
    "Aucune actualité.": "Nessuna notizia.",
    "Personne n'a mis de joueurs en vente": "Nessuno ha messo giocatori in vendita",
    "Aucun joueur pour ces filtres.": "Nessun giocatore per questi filtri.",
    "Aucun joueur dans l'effectif.": "Nessun giocatore in rosa.",
    "Aucun joueur dans cette liste pour l'instant.": "Nessun giocatore in questa lista ancora.",
    "Aucune proposition reçue": "Nessuna proposta ricevuta",
    "Aucune proposition envoyée": "Nessuna proposta inviata",
    "Aucune donnée de classement": "Nessun dato classifica",
    "Aucun actionnaire enregistré": "Nessun azionista registrato",
    "Aucune rumeur": "Nessuna voce",
    "Aucun match programmé.": "Nessuna partita programmata.",
    "Aucun rapport de recrutement pour l'instant.": "Nessun rapporto scouting ancora.",
    "Aucun recruteur. Recrutez le premier.": "Nessun osservatore. Ingaggia il primo.",
    "Aucune saison enregistrée.": "Nessuna stagione registrata.",
    "Aucun staff recruté": "Nessuno staff ingaggiato",
    "Aucun classement": "Nessuna classifica",
    "Pas encore de classement.": "Nessuna classifica ancora.",
    "Aucun résultat marquant cette journée.": "Nessun risultato di rilievo in questa giornata.",
    "Aucun objectif": "Nessun obiettivo",
    "Aucune équipe dans ce championnat pour l'instant.": "Nessuna squadra in questo campionato ancora.",
    "Aucune action entraînée": "Nessuna azione allenata",
    "OFFRE ACCEPTÉE": "OFFERTA ACCETTATA",
    "OFFRE REFUSÉE": "OFFERTA RIFIUTATA",
    "OUVERTE": "APERTA",
    "Offre retirée": "Offerta ritirata",
    "Piège du hors-jeu": "Trappola fuorigioco",
    "Ouvrir FDF Today": "Apri FDF Today",
    "Opération échouée": "Operazione fallita",
    "Centre des opérations": "Centro operazioni",
    "Opérations prêtes": "Operazioni pronte",
    "Composition optimale": "Formazione ottimale",
    "Composition optimale appliquée": "Formazione ottimale applicata",
    "Fonctionnement optimal": "Funzionamento ottimale",
    "Organisation": "Organizzazione",
    "Sous-traitance": "Outsourcing",
    "EN ATTENTE": "IN ATTESA",
    "Passe": "Passaggio",
    "Payer la clause libératoire": "Paga clausola rescissoria",
    "Les matchs en attente de la journée actuelle seront simulés. Cette action est irréversible.": "Le partite in sospeso della giornata attuale saranno simulate. Azione irreversibile.",
    "Personnalité": "Personalità",
    "Planter une rumeur (−120 prestige)": "Piantare voce (−120 prestigio)",
    "Joués": "Giocate",
    "Joueur": "Giocatore",
    "Joueur n°{{id}}": "Giocatore n.{{id}}",
    "Joueur promu en équipe première !": "Giocatore promosso in prima squadra!",
    "Joueur indisponible": "Giocatore non disponibile",
    "Joueurs en forme": "Giocatori in forma",
    "Joueurs en groupes": "Giocatori in gruppi",
    "Les joueurs sans club apparaîtront ici.": "I giocatori senza club appariranno qui.",
    "Joueurs que vous suivez. Assignés automatiquement aux recruteurs libres si disponibles.": "Giocatori che segui. Assegnati automaticamente agli osservatori liberi se disponibili.",
    "Poste": "Ruolo",
    "Position {{pos}}": "Posizione {{pos}}",
    "Position {{pos}}, {{club}}": "Posizione {{pos}}, {{club}}",
    "Potentiel {{potential}} · valeur {{value}}": "Potenziale {{potential}} · valore {{value}}",
    "Potentiel {{talent}}/99": "Potenziale {{talent}}/99",
    "Pré-saison": "Pre-stagione",
    "Préparer le prochain tour": "Prepara prossimo turno",
    "Préparation du résumé du tour…": "Preparazione riepilogo turno…",
    "Conférence de presse en attente": "Conferenza stampa in attesa",
    "Prestige": "Prestigio",
    "Prestige 2.0": "Prestigio 2.0",
    "Précédent": "Precedente",
    "Journée précédente": "Giornata precedente",
    "Mois précédent": "Mese precedente",
    "Contrat professionnel : {{name}}": "Contratto professionale: {{name}}",
    "Profil": "Profilo",
    "Progression vers le niveau {{level}}": "Progresso verso livello {{level}}",
    "Projection": "Proiezione",
    "Promouvoir": "Promuovi",
    "Échec de la promotion": "Promozione fallita",
    "Espoir": "Prospetto",
    "Espoir n°{{id}}": "Prospetto n.{{id}}",
    "Espoirs en développement": "Prospetti in sviluppo",
    "{{count}} actions achetées": "{{count}} azioni acquistate",
    "Quarts de finale": "Quarti di finale",
    "RIVAL DE LA SEMAINE": "RIVALE DELLA SETTIMANA",
    "Le classement n'a pas encore de données.": "La classifica non ha ancora dati.",
    "Note": "Voto",
    "Prêt pour une charge complète.": "Pronto per carico completo.",
    "Reçues": "Ricevute",
    "Derniers matchs": "Ultime partite",
    "Recommandé : {{name}}": "Consigliato: {{name}}",
    "Refuser la proposition": "Rifiuta proposta",
    "Refuser cette proposition ? Vous ne pourrez pas la récupérer.": "Rifiutare questa proposta? Non potrai recuperarla.",
    "Clause libératoire": "Clausola rescissoria",
    "Clause libératoire :": "Clausola rescissoria:",
    "Zone de relégation": "Zona retrocessione",
    "Zone de relégation, position {{pos}}": "Zona retrocessione, posizione {{pos}}",
    "Recharger": "Ricarica",
    "Retirer": "Rimuovi",
    "Retirer de la vente": "Rimuovi dalla vendita",
    "Retirer des objectifs": "Rimuovi dagli obiettivi",
    "Retirer ce joueur du mercato ?": "Rimuovere questo giocatore dal mercato?",
    "Retiré de la vente": "Rimosso dalla vendita",
    "Renouvellement accepté": "Rinnovo accettato",
    "Rapport approfondi": "Rapporto approfondito",
    "Réputation": "Reputazione",
    "Salaire initial requis": "Stipendio iniziale richiesto",
    "Réessayer": "Riprova",
    "Réessayer l'accès": "Riprova accesso",
    "Recettes": "Entrate",
    "Droitier": "Destro",
    "Rôle": "Ruolo",
    "Plan des chambres": "Pianta camere",
    "Huitièmes de finale": "Ottavi di finale",
    "Tour {{n}}": "Turno {{n}}",
    "Rumeur plantée dans la presse": "Voce piantata sulla stampa",
    "Rumeurs": "Voci",
    "PASSER EN 2D": "PASSA A 2D",
    "Offre salariale": "Offerta salariale",
    "Recruteur": "Osservatore",
    "Recruteur n°{{id}}": "Osservatore n.{{id}}",
    "Recruteur recruté": "Osservatore ingaggiato",
    "Joueurs recrutés": "Giocatori osservati",
    "Département du recrutement": "Dipartimento scouting",
    "Mission de recrutement créée": "Missione scouting creata",
    "Missions de recrutement": "Missioni scouting",
    "Zone de recrutement": "Zona scouting",
    "Recruteurs": "Osservatori",
    "Recruteur…": "Osservatore…",
    "Offre scellée n°{{id}}": "Offerta sigillata n.{{id}}",
    "Rechercher": "Cerca",
    "Saison": "Stagione",
    "Saison en cours": "Stagione in corso",
    "Voit la valorisation exacte des offres rivales": "Vede la valutazione esatta delle offerte rivali",
    "Sélectionnez une autre journée dans le navigateur supérieur.": "Seleziona un'altra giornata nel navigatore superiore.",
    "Demi-finales": "Semifinali",
    "Envoyer en recrutement": "Invia a scouting",
    "Envoi…": "Invio…",
    "Envoyées": "Inviate",
    "Serveur indisponible": "Server non disponibile",
    "Définir comme principale": "Imposta come principale",
    "Maître des coups de pied arrêtés": "Maestro dei calci piazzati",
    "Réglages": "Impostazioni",
    "Actions": "Azioni",
    "Actions requises": "Azioni richieste",
    "Tir": "Tiro",
    "Signer": "Firma",
    "Signer le contrat": "Firma contratto",
    "Objectifs de recrutement": "Obiettivi di ingaggio",
    "Simuler le match": "Simula partita",
    "Simuler maintenant": "Simula ora",
    "Simuler ce match maintenant ?": "Simulare questa partita ora?",
    "Simuler {{home}} vs {{away}} ?": "Simulare {{home}} vs {{away}}?",
    "Points de compétence": "Punti abilità",
    "Arbre de compétences": "Albero abilità",
    "Compétences": "Abilità",
    "Carte sociale générée": "Scheda social generata",
    "{{count}} actions vendues · {{proceeds}}": "{{count}} azioni vendute · {{proceeds}}",
    "Semer la crise dans le vestiaire": "Semina crisi nello spogliatoio",
    "Effectif": "Rosa",
    "Numéro": "Numero di maglia",
    "État de l'effectif": "Stato rosa",
    "Effectif indisponible": "Rosa non disponibile",
    "Stade indisponible": "Stadio non disponibile",
    "Vue du stade": "Vista stadio",
    "Membre du staff licencié": "Membro staff licenziato",
    "Structure du staff": "Struttura staff",
    "Classement": "Classifica",
    "Classement : {{league}}": "Classifica: {{league}}",
    "Commencez l'entraînement d'une action pour que votre équipe la maîtrise en match.": "Inizia l'allenamento di un'azione perché la squadra la padroneggi in partita.",
    "Titulaires": "Titolari",
    "Statistiques": "Statistiche",
    "Statut : indisponible": "Stato: non disponibile",
    "Ne plus suivre ce joueur ?": "Smettere di seguire questo giocatore?",
    "Style": "Stile",
    "Remplaçants": "Sostituti",
    "Suspendu": "Squalificato",
    "ENTRAÎNEMENT…": "ALLENAMENTO…",
    "Tacle": "Contrasto",
    "Génie tactique": "Genio tattico",
    "Tactique": "Tattica",
    "Tableau tactique, actions et match": "Lavagna tattica, azioni e partita",
    "Tactique enregistrée avec succès": "Tattica salvata con successo",
    "Tactique définie comme principale": "Tattica impostata come principale",
    "Objectif": "Obiettivo",
    "Club cible": "Club obiettivo",
    "Club cible…": "Club obiettivo…",
    "Gestion du personnel de l'équipe": "Gestione personale squadra",
    "Actions du club": "Azioni del club",
    "Discours d'équipe appliqué": "Discorso squadra applicato",
    "Discours technique": "Discorso tecnico",
    "Approbation de la mise à niveau technologique": "Approvazione upgrade tecnologico",
    "Tension": "Tensione",
    "Le monde FDF a franchi une étape de plus.": "Il mondo FDF ha fatto un passo avanti.",
    "La journée": "La giornata",
    "Le club est à jour. Consultez la une et préparez le prochain match.": "Il club è aggiornato. Controlla la prima pagina e prepara la prossima partita.",
    "Le module financier n'a pas encore renvoyé de données.": "Il modulo finanziario non ha ancora restituito dati.",
    "L'étage illuminé marque le progrès technologique de votre académie. Chaque niveau augmente la moyenne de base des jeunes.": "Il piano illuminato segna il progresso tecnologico dell'accademia. Ogni livello aumenta la media base dei giovani.",
    "Le mercato est très calme cette semaine.": "Il mercato è molto calmo questa settimana.",
    "L'événement de la journée": "L'evento della giornata",
    "Les chiffres racontent l'histoire du projet : caisse, masse salariale et perspectives. Ce n'est pas un tableau BI — c'est le rapport que lirait la presse sportive.": "I numeri raccontano la storia del progetto: cassa, massa salariale e prospettive. Non è un pannello BI — è il report che leggerebbe la stampa sportiva.",
    "Le joueur refuse le renouvellement.": "Il giocatore rifiuta il rinnovo.",
    "Le joueur refusera cette offre.": "Il giocatore rifiuterà questa offerta.",
    "Troisième maillot": "Terza maglia",
    "Cela masquera votre tactique aux rivaux pendant 3 tours, mais consommera une charge de directive.": "Nasconderà la tattica ai rivali per 3 turni, ma consumerà una carica direttiva.",
    "Billetterie": "Biglietteria",
    "La une du jour est prête dans votre club.": "La prima pagina di oggi è pronta nel tuo club.",
    "Titres de demain": "Titoli di domani",
    "Meilleurs buteurs": "Capocannonieri",
    "Changement total enregistré": "Cambio totale registrato",
    "Effectif du staff": "Totale staff",
    "Tournoi": "Torneo",
    "Entraîner": "Allena",
    "Actions entraînées": "Azioni allenate",
    "Entraînement": "Allenamento",
    "Centre d'entraînement": "Centro allenamento",
    "Entraînement fermé": "Allenamento chiuso",
    "Entraînement «{{type}}»": "Allenamento «{{type}}»",
    "Entraînement…": "Allenamento…",
    "Fenêtre de transferts": "Finestra di mercato",
    "Transferts": "Trasferimenti",
    "Tour {{turn}}": "Turno {{turn}}",
    "Tour {{turn}}. Fermer l'entraînement (3t) ou donner un discours à domicile (2t). Coût de directive après usage 2.": "Turno {{turn}}. Chiudi allenamento (3t) o fai discorso in casa (2t). Costo direttiva dopo uso 2.",
    "Équipe U19": "Rosa U19",
    "En travaux": "In costruzione",
    "Rôles uniques": "Ruoli unici",
    "Débloquer": "Sblocca",
    "Prochains matchs": "Prossime partite",
    "Évoluer": "Evolvi",
    "Échec de l'amélioration (fonds insuffisants ?)": "Miglioramento fallito (fondi insufficienti?)",
    "Améliorer la technologie": "Migliora tecnologia",
    "Améliorations et extensions": "Miglioramenti e ampliamenti",
    "Utilisez « Proposer un transfert » pour ouvrir des négociations formelles avec un autre club.": "Usa « Proponi trasferimento » per aprire trattative formali con un altro club.",
    "VOIR EN 3D": "VEDI IN 3D",
    "VOIR PORTRAIT": "VEDI RITRATTO",
    "Valeur": "Valore",
    "Voir le match": "Vedi partita",
    "Voir offres et postes →": "Vedi offerte e posti →",
    "Votez pour l'action la plus spectaculaire de la communauté et laissez votre empreinte dans la chronique.": "Vota l'azione più spettacolare della community e lascia il segno nella cronaca.",
    "Vote ouvert": "Votazione aperta",
    "SEMAINE {{week}}": "SETTIMANA {{week}}",
    "FENÊTRE": "FINESTRA",
    "Salaire": "Stipendio",
    "Salaire/mois": "Stipendio/mese",
    "Missions hebdomadaires": "Missioni settimanali",
    "Pendant votre absence": "Mentre eri assente",
    "Améliorera le moral et la performance au prochain match à domicile, en consommant une charge de directive.": "Migliorerà morale e prestazione nella prossima partita in casa, consumando una carica direttiva.",
    "Fenêtre fermée : le serveur le refusera.": "Finestra chiusa: il server rifiuterà.",
    "Retirer l'offre": "Ritira offerta",
    "Retirer le joueur": "Ritira giocatore",
    "Retirer cette offre du mercato ? Vous ne pourrez pas la récupérer.": "Ritirare questa offerta dal mercato? Non potrai recuperarla.",
    "Travaux en cours": "Lavori in corso",
    "Années (1-5)": "Anni (1-5)",
    "Années restantes": "Anni rimanenti",
    "Oui, fermer": "Sì, chiudi",
    "Oui, donner le discours": "Sì, fai il discorso",
    "Vous": "Tu",
    "Vous avez perdu {{count}} place": "Hai perso {{count}} posizione",
    "Vous avez perdu {{count}} places": "Hai perso {{count}} posizioni",
    "Vous n'avez aucun staff recruté pour l'instant. Utilisez « Recruter du staff » pour signer des candidats.": "Non hai staff ingaggiato al momento. Usa « Ingaggia staff » per firmare candidati.",
    "Vous n'avez que {{owned}} actions": "Hai solo {{owned}} azioni",
    "Vous avez gagné {{count}} place": "Hai guadagnato {{count}} posizione",
    "Vous avez gagné {{count}} places": "Hai guadagnato {{count}} posizioni",
    "Vous paierez {{amount}} pour la clause libératoire de {{player}}. Cette opération est irrévocable.": "Pagherai {{amount}} per la clausola rescissoria di {{player}}. Operazione irrevocabile.",
    "Vous dépenserez 120 points de prestige pour semer la discorde dans le vestiaire adverse. Maximum 1 par semaine.": "Spenderai 120 punti prestigio per seminare discordia nello spogliatoio avversario. Massimo 1 a settimana.",
    "Votre offre": "La tua offerta",
    "Votre offre doit dépasser l'actuelle.": "La tua offerta deve superare quella attuale.",
    "Votre match est encore scellé. Ouvrez-le quand vous voulez.": "La tua partita è ancora sigillata. Aprila quando vuoi.",
    "Vos matchs": "Le tue partite",
    "Votre effectif, face à face": "La tua rosa, faccia a faccia",
    "Votre série :": "La tua serie:",
    "Vos offres de transfert apparaîtront ici.": "Le tue offerte di trasferimento appariranno qui.",
    "Zone…": "Zona…",
    "pts d'attribut": "pt attributo",
    "note moy.": "voto med.",
    "extension des dortoirs (+10 places)": "ampliamento dormitori (+10 posti)",
    "mise à niveau des installations (Niveau +1)": "upgrade strutture (Livello +1)",
    "mois restants": "mesi rimanenti",
    "occupation": "occupazione",
    "sur {{max}}": "di {{max}}",
    "recruteur": "osservatore",
    "scellée": "sigillata",
    "places": "posti",
    "l'indicateur du manager": "l'indicatore del manager",
    "jusqu'au {{date}}": "fino al {{date}}",
    "{{active}}/{{max}} en match": "{{active}}/{{max}} in partita",
    "{{club}} propose {{amount}}": "{{club}} offre {{amount}}",
    "{{count}} module actif": "{{count}} modulo attivo",
    "{{count}} modules actifs": "{{count}} moduli attivi",
    "{{count}} offre sur le mercato": "{{count}} offerta sul mercato",
    "{{count}} offres sur le mercato": "{{count}} offerte sul mercato",
    "{{count}} matchs": "{{count}} partite",
    "{{count}} j.": "{{count}} gioc.",
    "{{count}} message non lu": "{{count}} messaggio non letto",
    "{{count}} messages non lus": "{{count}} messaggi non letti",
    "{{count}} ans": "{{count}} anni",
    "{{count}} jeune prêt à être promu": "{{count}} giovane pronto alla promozione",
    "{{count}} jeunes prêts à être promus": "{{count}} giovani pronti alla promozione",
    "{{fee}} prime de signature": "{{fee}} bonus firma",
    "{{name}} ne peut pas jouer (blessure/suspension)": "{{name}} non può giocare (infortunio/squalifica)",
    "{{name}} recruté": "{{name}} ingaggiato",
    "{{name}} mène la une avec la note {{rating}}.": "{{name}} guida la prima pagina con voto {{rating}}.",
    "{{name}} a joué son match :": "{{name}} ha giocato la sua partita:",
    "{{occupied}} / {{capacity}} occupées": "{{occupied}} / {{capacity}} occupate",
    "{{player}} est à vous via la clause libératoire !": "{{player}} è tuo via clausola rescissoria!",
    "{{player}} prêté à {{club}}": "{{player}} prestato a {{club}}",
    "{{player}} signe pour {{years}} ans": "{{player}} firma per {{years}} anni",
    "· Moyenne de base = niveau de résidence × 3 + aléa(−5..25) − aléa(0..résidences) + 13 + valeur d'emplacement (1-20). Plafonnée entre 20 et 75.": "· Media base = livello residenza × 3 + random(−5..25) − random(0..residenze) + 13 + valore ubicazione (1-20). Limitata tra 20 e 75.",
    "· Chaque attribut = moyenne − 50 + aléa(0..30) − pénalité de poste.": "· Ogni attributo = media − 50 + random(0..30) − penalità ruolo.",
    "· Tous les ~3 mois de jeu, un joueur sort par résidence (vous pouvez choisir son poste).": "· Ogni ~3 mesi di gioco esce un giocatore per residenza (puoi scegliere il ruolo).",
    "· Limite mondiale annuelle : 3 joueurs à 7 barres et 21 à 6 barres. Les emblématiques retraités ajoutent un bonus.": "· Limite mondiale annuale: 3 giocatori a 7 barre e 21 a 6 barre. Icone ritirate aggiungono bonus.",
    "· Talent (plafond) = attribut + 50 + aléa(0..15). La cité sportive élève la fourchette (sans elle 15-60 ; niveau 8 : 43-84).": "· Talento (tetto) = attributo + 50 + random(0..15). La città sportiva alza il range (senza 15-60; livello 8: 43-84).",
    "· fermée": "· chiusa",
    "· jouée": "· giocata",
    "· {{count}} point disponible": "· {{count}} punto disponibile",
    "· {{count}} points disponibles": "· {{count}} punti disponibili",
    "150 000 €": "150.000 €",
    "250 000 €": "250.000 €",
    "/mois": "/mese",
    "⇄ {{in}} entre pour {{out}}": "⇄ {{in}} entra al posto di {{out}}",
    "⚠️ Protocole de récupération requis.": "⚠️ Richiede protocollo di recupero.",
    "🏥 Blessé": "🏥 Infortunato",
    "🟥 Suspendu": "🟥 Squalificato",
}


def fr_to_it(fr: str) -> str:
    if fr in FR_TO_IT:
        return FR_TO_IT[fr]
    protected, tokens = protect(fr)
    result = protected
    for src, dst in sorted(FR_TO_IT.items(), key=lambda x: -len(x[0])):
        result = result.replace(src, dst)
    return restore(result, tokens)


def main() -> None:
    it_glossary: dict[str, str] = {}
    for en, fr in FR_GLOSSARY.items():
        it_glossary[en] = fr_to_it(fr)
    # Manual fixes where FR->IT mapping left French
    IT_FIXES = {
        "Rapport approfondi": "Rapporto approfondito",
    }
    it_glossary.update({en: IT_FIXES.get(v, v) for en, v in it_glossary.items() if v in IT_FIXES})
    for en, fix in IT_FIXES.items():
        if en in FR_GLOSSARY:
            it_glossary[en] = fix

    out = SCRIPTS / "gameplay_i18n_it_glossary.json"
    out.write_text(json.dumps(it_glossary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(it_glossary)} IT entries")


if __name__ == "__main__":
    main()
