-- AlterTable
ALTER TABLE "PlayerMatchStat" ADD COLUMN "shotsOnTarget" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerMatchStat" ADD COLUMN "passesCompleted" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerMatchStat" ADD COLUMN "passAccuracy" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PlayerMatchStat" ADD COLUMN "tackles" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerMatchStat" ADD COLUMN "interceptions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PlayerMatchStat" ADD COLUMN "keyPasses" INTEGER NOT NULL DEFAULT 0;
